//.$file${./ClusterControl~::Cluster.cpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: ClusterController.qm
// File:  ${./ClusterControl~::Cluster.cpp}
//
// This code has been generated by QM 5.1.3 <www.state-machine.com/qm/>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// This program is open source software: you can redistribute it and/or
// modify it under the terms of the GNU General Public License as published
// by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
// for more details.
//
//.$endhead${./ClusterControl~::Cluster.cpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "ClusterController.hpp"  // ClusterController application interface


using namespace QP;

//============================================================================
// generate declaration of the active object
//.$declare${AOs::Cluster} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace CC {

//.${AOs::Cluster} ...........................................................
class Cluster : public QP::QActive {
public:
    static Cluster instance;

public:
    Cluster();

protected:
    Q_STATE_DECL(initial);
    Q_STATE_DECL(ClusterOn);
    Q_STATE_DECL(PowerOn);
    Q_STATE_DECL(PowerOff);
};

} // namespace CC
//.$enddecl${AOs::Cluster} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//============================================================================
// generate definition of to opaque pointer to the AO
//.$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//. Check for the minimum required QP version
#if (QP_VERSION < 690U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpcpp version 6.9.0 or higher required
#endif
//.$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//.$define${Shared::AO_Cluster} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace CC {

//.${Shared::AO_Cluster} .....................................................
QP::QActive * const AO_Cluster = &Cluster::instance;

} // namespace CC
//.$enddef${Shared::AO_Cluster} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//============================================================================
// generate definition of the AO
//.$define${AOs::Cluster} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace CC {

//.${AOs::Cluster} ...........................................................
Cluster Cluster::instance;
//.${AOs::Cluster::Cluster} ..................................................
Cluster::Cluster()
: QActive(Q_STATE_CAST(&Cluster::initial))
{}

//.${AOs::Cluster::SM} .......................................................
Q_STATE_DEF(Cluster, initial) {
    //.${AOs::Cluster::SM::initial}
    BSP::initializeCluster();
    subscribe(RESET_SIG);
    subscribe(POWER_ON_SIG);
    subscribe(POWER_OFF_SIG);
    return tran(&ClusterOn);
}
//.${AOs::Cluster::SM::ClusterOn} ............................................
Q_STATE_DEF(Cluster, ClusterOn) {
    QP::QState status_;
    switch (e->sig) {
        //.${AOs::Cluster::SM::ClusterOn}
        case Q_ENTRY_SIG: {
            BSP::activateCommandInterfaces();
            status_ = Q_RET_HANDLED;
            break;
        }
        //.${AOs::Cluster::SM::ClusterOn}
        case Q_EXIT_SIG: {
            BSP::deactivateCommandInterfaces();
            status_ = Q_RET_HANDLED;
            break;
        }
        //.${AOs::Cluster::SM::ClusterOn::initial}
        case Q_INIT_SIG: {
            status_ = tran(&PowerOff);
            break;
        }
        //.${AOs::Cluster::SM::ClusterOn::RESET}
        case RESET_SIG: {
            status_ = tran(&ClusterOn);
            break;
        }
        //.${AOs::Cluster::SM::ClusterOn::POWER_OFF}
        case POWER_OFF_SIG: {
            status_ = tran(&PowerOff);
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}
//.${AOs::Cluster::SM::ClusterOn::PowerOn} ...................................
Q_STATE_DEF(Cluster, PowerOn) {
    QP::QState status_;
    switch (e->sig) {
        //.${AOs::Cluster::SM::ClusterOn::PowerOn}
        case Q_ENTRY_SIG: {
            BSP::powerOn();
            status_ = Q_RET_HANDLED;
            break;
        }
        default: {
            status_ = super(&ClusterOn);
            break;
        }
    }
    return status_;
}
//.${AOs::Cluster::SM::ClusterOn::PowerOff} ..................................
Q_STATE_DEF(Cluster, PowerOff) {
    QP::QState status_;
    switch (e->sig) {
        //.${AOs::Cluster::SM::ClusterOn::PowerOff}
        case Q_ENTRY_SIG: {
            BSP::powerOff();
            status_ = Q_RET_HANDLED;
            break;
        }
        //.${AOs::Cluster::SM::ClusterOn::PowerOff::POWER_ON}
        case POWER_ON_SIG: {
            status_ = tran(&PowerOn);
            break;
        }
        default: {
            status_ = super(&ClusterOn);
            break;
        }
    }
    return status_;
}

} // namespace CC
//.$enddef${AOs::Cluster} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
