//.$file${./ClusterControl~::ClusterController.cpp} vvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: ClusterController.qm
// File:  ${./ClusterControl~::ClusterController.cpp}
//
// This code has been generated by QM 5.1.3 <www.state-machine.com/qm/>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// This program is open source software: you can redistribute it and/or
// modify it under the terms of the GNU General Public License as published
// by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
// for more details.
//
//.$endhead${./ClusterControl~::ClusterController.cpp} ^^^^^^^^^^^^^^^^^^^^^^^
#include "ClusterController.hpp"  // ClusterController application interface

using namespace QP;

namespace ArduinoInterface {

//............................................................................
void setup() {

    QF::init(); // initialize the framework
    BSP::init(); // initialize the BSP

    // init publish-subscribe
    static QSubscrList subscrSto[CC::MAX_PUB_SIG];
    QF::psInit(subscrSto, Q_DIM(subscrSto));

    // statically allocate event queues for the AOs and start them...
    static QEvt const *watchdog_queueSto[2];
    CC::AO_Watchdog->start(1U, // priority
        watchdog_queueSto, Q_DIM(watchdog_queueSto),
        (void *)0, 0U); // no stack

    static QEvt const *serial_command_interface_queueSto[10];
    CC::AO_SerialCommandInterface->start(2U, // priority
        serial_command_interface_queueSto, Q_DIM(serial_command_interface_queueSto),
        (void *)0, 0U); // no stack

    static QEvt const *ethernet_command_interface_queueSto[10];
    CC::AO_EthernetCommandInterface->start(3U, // priority
        ethernet_command_interface_queueSto, Q_DIM(ethernet_command_interface_queueSto),
        (void *)0, 0U); // no stack

    static QEvt const *cluster_queueSto[10];
    CC::AO_Cluster->start(4U, // priority
        cluster_queueSto, Q_DIM(cluster_queueSto),
        (void *)0, 0U); // no stack

   //...
}

//............................................................................
void loop() {
    QF::run(); // run the QF/C++ framework
}

} // namespace AC