//.$file${./ClusterControl~::EthernetCommandInterface.cpp} vvvvvvvvvvvvvvvvvvv
//
// Model: ClusterController.qm
// File:  ${./ClusterControl~::EthernetCommandInterface.cpp}
//
// This code has been generated by QM 5.1.3 <www.state-machine.com/qm/>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// This program is open source software: you can redistribute it and/or
// modify it under the terms of the GNU General Public License as published
// by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
// for more details.
//
//.$endhead${./ClusterControl~::EthernetCommandInterface.cpp} ^^^^^^^^^^^^^^^^
#include "EthernetCommandInterface.hpp"


using namespace QP;

//============================================================================
// generate definition of to opaque pointer to the AO
//.$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//. Check for the minimum required QP version
#if (QP_VERSION < 690U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpcpp version 6.9.0 or higher required
#endif
//.$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//.$define${Shared::AO_EthernetCommandInterface} vvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace CC {

//.${Shared::AO_EthernetCommandInterface} ....................................
QP::QActive * const AO_EthernetCommandInterface = &EthernetCommandInterface::instance;

} // namespace CC
//.$enddef${Shared::AO_EthernetCommandInterface} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//============================================================================
// generate definition of the AO
//.$define${AOs::EthernetCommandInterface} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace CC {

//.${AOs::EthernetCommandInterface} ..........................................
EthernetCommandInterface EthernetCommandInterface::instance;
//.${AOs::EthernetCommandI~::EthernetCommandInterface} .......................
EthernetCommandInterface::EthernetCommandInterface()
: QActive(Q_STATE_CAST(&EthernetCommandInterface::initial)),
    ethernet_time_evt_(this, ETHERNET_TIMEOUT_SIG, 0U)
{}

//.${AOs::EthernetCommandI~::SM} .............................................
Q_STATE_DEF(EthernetCommandInterface, initial) {
    //.${AOs::EthernetCommandI~::SM::initial}
    FSP::EthernetCommandInterface_initializeAndSubscribe(this, e);

    QS_FUN_DICTIONARY(&EthernetCommandInterface::Inactive);
    QS_FUN_DICTIONARY(&EthernetCommandInterface::Active);
    QS_FUN_DICTIONARY(&EthernetCommandInterface::Unintitalized);
    QS_FUN_DICTIONARY(&EthernetCommandInterface::Initialized);
    QS_FUN_DICTIONARY(&EthernetCommandInterface::ServerRunning);

    return tran(&Inactive);
}
//.${AOs::EthernetCommandI~::SM::Inactive} ...................................
Q_STATE_DEF(EthernetCommandInterface, Inactive) {
    QP::QState status_;
    switch (e->sig) {
        //.${AOs::EthernetCommandI~::SM::Inactive::ACTIVATE_ETHERNET_COMMAND_INTERF~}
        case ACTIVATE_ETHERNET_COMMAND_INTERFACE_SIG: {
            status_ = tran(&Active);
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}
//.${AOs::EthernetCommandI~::SM::Active} .....................................
Q_STATE_DEF(EthernetCommandInterface, Active) {
    QP::QState status_;
    switch (e->sig) {
        //.${AOs::EthernetCommandI~::SM::Active}
        case Q_ENTRY_SIG: {
            FSP::EthernetCommandInterface_armEthernetTimer(this, e);
            status_ = Q_RET_HANDLED;
            break;
        }
        //.${AOs::EthernetCommandI~::SM::Active}
        case Q_EXIT_SIG: {
            FSP::EthernetCommandInterface_disarmEthernetTimer(this, e);
            status_ = Q_RET_HANDLED;
            break;
        }
        //.${AOs::EthernetCommandI~::SM::Active::initial}
        case Q_INIT_SIG: {
            status_ = tran(&Unintitalized);
            break;
        }
        //.${AOs::EthernetCommandI~::SM::Active::DEACTIVATE_ETHERNET_COMMAND_INTE~}
        case DEACTIVATE_ETHERNET_COMMAND_INTERFACE_SIG: {
            status_ = tran(&Inactive);
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}
//.${AOs::EthernetCommandI~::SM::Active::Unintitalized} ......................
Q_STATE_DEF(EthernetCommandInterface, Unintitalized) {
    QP::QState status_;
    switch (e->sig) {
        //.${AOs::EthernetCommandI~::SM::Active::Unintitalized::ETHERNET_INITIALIZED}
        case ETHERNET_INITIALIZED_SIG: {
            status_ = tran(&Initialized);
            break;
        }
        //.${AOs::EthernetCommandI~::SM::Active::Unintitalized::ETHERNET_TIMEOUT}
        case ETHERNET_TIMEOUT_SIG: {
            FSP::EthernetCommandInterface_beginEthernet(this, e);
            status_ = Q_RET_HANDLED;
            break;
        }
        default: {
            status_ = super(&Active);
            break;
        }
    }
    return status_;
}
//.${AOs::EthernetCommandI~::SM::Active::Initialized} ........................
Q_STATE_DEF(EthernetCommandInterface, Initialized) {
    QP::QState status_;
    switch (e->sig) {
        //.${AOs::EthernetCommandI~::SM::Active::Initialized::ETHERNET_SERVER_INITIALIZED}
        case ETHERNET_SERVER_INITIALIZED_SIG: {
            status_ = tran(&ServerRunning);
            break;
        }
        //.${AOs::EthernetCommandI~::SM::Active::Initialized::ETHERNET_TIMEOUT}
        case ETHERNET_TIMEOUT_SIG: {
            FSP::EthernetCommandInterface_beginServer(this, e);
            status_ = Q_RET_HANDLED;
            break;
        }
        default: {
            status_ = super(&Active);
            break;
        }
    }
    return status_;
}
//.${AOs::EthernetCommandI~::SM::Active::ServerRunning} ......................
Q_STATE_DEF(EthernetCommandInterface, ServerRunning) {
    QP::QState status_;
    switch (e->sig) {
        //.${AOs::EthernetCommandI~::SM::Active::ServerRunning::ETHERNET_TIMEOUT}
        case ETHERNET_TIMEOUT_SIG: {
            FSP::EthernetCommandInterface_pollEthernetCommand(this, e);
            status_ = Q_RET_HANDLED;
            break;
        }
        default: {
            status_ = super(&Active);
            break;
        }
    }
    return status_;
}

} // namespace CC
//.$enddef${AOs::EthernetCommandInterface} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
