//.$file${./ClusterControl~::Prism.cpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: ClusterController.qm
// File:  ${./ClusterControl~::Prism.cpp}
//
// This code has been generated by QM 5.1.3 <www.state-machine.com/qm/>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// This program is open source software: you can redistribute it and/or
// modify it under the terms of the GNU General Public License as published
// by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
// for more details.
//
//.$endhead${./ClusterControl~::Prism.cpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "Prism.hpp"

Q_DEFINE_THIS_FILE

using namespace QP;

//============================================================================
// generate definition of the class
//.$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//. Check for the minimum required QP version
#if (QP_VERSION < 690U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpcpp version 6.9.0 or higher required
#endif
//.$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//.$define${Shared::Prism_getInstance} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace CC {

//.${Shared::Prism_getInstance} ..............................................
QP::QHsm * Prism_getInstance(std::uint8_t prism_address) {
    Q_REQUIRE(prism_address < Q_DIM(Prism::instances));
    return &Prism::instances[prism_address];
}

} // namespace CC
//.$enddef${Shared::Prism_getInstance} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//.$define${AOs::Prism} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace CC {

//.${AOs::Prism} .............................................................
Prism Prism::instances[constants::prism_count_max];
//.${AOs::Prism::SM} .........................................................
Q_STATE_DEF(Prism, initial) {
    //.${AOs::Prism::SM::initial}
    FSP::Prism_initialize(this, e);

    QS_FUN_DICTIONARY(&Prism::PoweredOff);
    QS_FUN_DICTIONARY(&Prism::PoweredOn);
    QS_FUN_DICTIONARY(&Prism::NotSetup);
    QS_FUN_DICTIONARY(&Prism::SetupAndCommunicating);
    QS_FUN_DICTIONARY(&Prism::Enabled);
    QS_FUN_DICTIONARY(&Prism::Homing);
    QS_FUN_DICTIONARY(&Prism::Homed);
    QS_FUN_DICTIONARY(&Prism::Disconnected);

    return tran(&PoweredOff);
}
//.${AOs::Prism::SM::PoweredOff} .............................................
Q_STATE_DEF(Prism, PoweredOff) {
    QP::QState status_;
    switch (e->sig) {
        //.${AOs::Prism::SM::PoweredOff::POWER_ON}
        case POWER_ON_SIG: {
            status_ = tran(&PoweredOn);
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}
//.${AOs::Prism::SM::PoweredOn} ..............................................
Q_STATE_DEF(Prism, PoweredOn) {
    QP::QState status_;
    switch (e->sig) {
        //.${AOs::Prism::SM::PoweredOn::initial}
        case Q_INIT_SIG: {
            status_ = tran(&NotSetup);
            break;
        }
        //.${AOs::Prism::SM::PoweredOn::POWER_OFF}
        case POWER_OFF_SIG: {
            status_ = tran(&PoweredOff);
            break;
        }
        //.${AOs::Prism::SM::PoweredOn::RESET}
        case RESET_SIG: {
            status_ = tran(&PoweredOff);
            break;
        }
        //.${AOs::Prism::SM::PoweredOn::CLUSTER_TIMEOUT}
        case CLUSTER_TIMEOUT_SIG: {
            status_ = Q_RET_HANDLED;
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}
//.${AOs::Prism::SM::PoweredOn::NotSetup} ....................................
Q_STATE_DEF(Prism, NotSetup) {
    QP::QState status_;
    switch (e->sig) {
        //.${AOs::Prism::SM::PoweredOn::NotSetup::CLUSTER_TIMEOUT}
        case CLUSTER_TIMEOUT_SIG: {
            FSP::Prism_setup(this, e);
            //.${AOs::Prism::SM::PoweredOn::NotSetup::CLUSTER_TIMEOUT::[communicating()]}
            if (FSP::Prism_communicating(this, e)) {
                status_ = tran(&SetupAndCommunicating);
            }
            //.${AOs::Prism::SM::PoweredOn::NotSetup::CLUSTER_TIMEOUT::[else]}
            else {
                status_ = tran(&Disconnected);
            }
            break;
        }
        default: {
            status_ = super(&PoweredOn);
            break;
        }
    }
    return status_;
}
//.${AOs::Prism::SM::PoweredOn::SetupAndCommunicating} .......................
Q_STATE_DEF(Prism, SetupAndCommunicating) {
    QP::QState status_;
    switch (e->sig) {
        //.${AOs::Prism::SM::PoweredOn::SetupAndCommunicating}
        case Q_ENTRY_SIG: {
            FSP::Prism_recordSetupAndCommunicating(this, e);
            status_ = Q_RET_HANDLED;
            break;
        }
        //.${AOs::Prism::SM::PoweredOn::SetupAndCommunic~::initial}
        case Q_INIT_SIG: {
            FSP::Prism_setupParametersAndEnable(this, e);
            status_ = tran(&Enabled);
            break;
        }
        //.${AOs::Prism::SM::PoweredOn::SetupAndCommunic~::HOME_PRISM}
        case HOME_PRISM_SIG: {
            FSP::Prism_beginHome(this, e);
            status_ = tran(&Homing);
            break;
        }
        default: {
            status_ = super(&PoweredOn);
            break;
        }
    }
    return status_;
}
//.${AOs::Prism::SM::PoweredOn::SetupAndCommunic~::Enabled} ..................
Q_STATE_DEF(Prism, Enabled) {
    QP::QState status_;
    switch (e->sig) {
        default: {
            status_ = super(&SetupAndCommunicating);
            break;
        }
    }
    return status_;
}
//.${AOs::Prism::SM::PoweredOn::SetupAndCommunic~::Homing} ...................
Q_STATE_DEF(Prism, Homing) {
    QP::QState status_;
    switch (e->sig) {
        //.${AOs::Prism::SM::PoweredOn::SetupAndCommunic~::Homing::CLUSTER_TIMEOUT}
        case CLUSTER_TIMEOUT_SIG: {
            FSP::Prism_homed(this, e);
            status_ = Q_RET_HANDLED;
            break;
        }
        //.${AOs::Prism::SM::PoweredOn::SetupAndCommunic~::Homing::PRISM_HOMED}
        case PRISM_HOMED_SIG: {
            status_ = tran(&Homed);
            break;
        }
        default: {
            status_ = super(&SetupAndCommunicating);
            break;
        }
    }
    return status_;
}
//.${AOs::Prism::SM::PoweredOn::SetupAndCommunic~::Homed} ....................
Q_STATE_DEF(Prism, Homed) {
    QP::QState status_;
    switch (e->sig) {
        //.${AOs::Prism::SM::PoweredOn::SetupAndCommunic~::Homed}
        case Q_ENTRY_SIG: {
            FSP::Prism_recordHomed(this, e);
            status_ = Q_RET_HANDLED;
            break;
        }
        default: {
            status_ = super(&SetupAndCommunicating);
            break;
        }
    }
    return status_;
}
//.${AOs::Prism::SM::PoweredOn::Disconnected} ................................
Q_STATE_DEF(Prism, Disconnected) {
    QP::QState status_;
    switch (e->sig) {
        //.${AOs::Prism::SM::PoweredOn::Disconnected}
        case Q_ENTRY_SIG: {
            FSP::Prism_recordDisconnected(this, e);
            status_ = Q_RET_HANDLED;
            break;
        }
        default: {
            status_ = super(&PoweredOn);
            break;
        }
    }
    return status_;
}

} // namespace CC
//.$enddef${AOs::Prism} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
