//.$file${./ClusterControl~::Prism.cpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: ClusterController.qm
// File:  ${./ClusterControl~::Prism.cpp}
//
// This code has been generated by QM 5.1.3 <www.state-machine.com/qm/>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// This program is open source software: you can redistribute it and/or
// modify it under the terms of the GNU General Public License as published
// by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
// for more details.
//
//.$endhead${./ClusterControl~::Prism.cpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "Prism.hpp"

Q_DEFINE_THIS_FILE

using namespace QP;

namespace CC
{
// helper function to provide the address of this prism ............................
static inline uint8_t PRISM_ADDRESS(Prism const * const me)
{
  return static_cast<uint8_t>(me - &Prism::instances[0]);
}

} // namespace CC

//============================================================================
// generate definition of the class
//.$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//. Check for the minimum required QP version
#if (QP_VERSION < 690U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpcpp version 6.9.0 or higher required
#endif
//.$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//.$define${Shared::Prism_getInstance} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace CC {

//.${Shared::Prism_getInstance} ..............................................
QP::QHsm * Prism_getInstance(std::uint8_t prism_address) {
    Q_REQUIRE(prism_address < Q_DIM(Prism::instances));
    return &Prism::instances[prism_address];
}

} // namespace CC
//.$enddef${Shared::Prism_getInstance} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//.$define${AOs::Prism} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace CC {

//.${AOs::Prism} .............................................................
Prism Prism::instances[constants::prism_count_max];
//.${AOs::Prism::SM} .........................................................
Q_STATE_DEF(Prism, initial) {
    //.${AOs::Prism::SM::initial}
    FSP::Prism_initialize(this, e);

    QS_FUN_DICTIONARY(&Prism::UnHomed);

    return tran(&UnHomed);
}
//.${AOs::Prism::SM::UnHomed} ................................................
Q_STATE_DEF(Prism, UnHomed) {
    QP::QState status_;
    switch (e->sig) {
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}

} // namespace CC
//.$enddef${AOs::Prism} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
