//.$file${.::ClusterController.hpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: ClusterController.qm
// File:  ${.::ClusterController.hpp}
//
// This code has been generated by QM 5.1.3 <www.state-machine.com/qm/>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// This program is open source software: you can redistribute it and/or
// modify it under the terms of the GNU General Public License as published
// by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
// for more details.
//
//.$endhead${.::ClusterController.hpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef CLUSTER_CONTROLLER_HPP
#define CLUSTER_CONTROLLER_HPP

#include "qpcpp.hpp"
#include "fsp.hpp"


namespace ArduinoInterface
{
void setup();
void loop();
}

//.$declare${Shared} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace CC {

//.${Shared::CommandEvt} .....................................................
class CommandEvt : public QP::QEvt {};
//.${Shared::EthernetCommandEvt} .............................................
class EthernetCommandEvt : public QP::QEvt {
public:
    void * connection;
    std::uint8_t const * binary_command;
    std::uint32_t binary_command_byte_count;
};
//.${Shared::PrismCommandEvt} ................................................
class PrismCommandEvt : public QP::QEvt {
public:
    std::uint8_t prism_address;
};
extern QP::QActive * const AO_Cluster;
extern QP::QActive * const AO_SerialCommandInterface;
extern QP::QActive * const AO_EthernetCommandInterface;
extern QP::QActive * const AO_Watchdog;
//.${Shared::Prism_getInstance} ..............................................
QP::QHsm * Prism_getInstance(std::uint8_t prism_address) ;

} // namespace CC
//.$enddecl${Shared} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif