//$file${.::Cluster.hpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: ClusterController.qm
// File:  ${.::Cluster.hpp}
//
// This code has been generated by QM 5.2.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::Cluster.hpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef CLUSTER_HPP
#define CLUSTER_HPP

#include "ClusterController.hpp"


//============================================================================
// generate declaration of the active object
//$declare${AOs::Cluster} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace CC {

//${AOs::Cluster} ............................................................
class Cluster : public QP::QActive {
public:
    static Cluster instance;
    QP::QHsm * prisms_[constants::prism_count_max];
    QP::QTimeEvt cluster_time_evt_;
    std::uint8_t run_current_;
    std::uint8_t start_velocity_;
    std::uint8_t stop_velocity_;
    std::uint8_t first_velocity_;
    std::uint8_t max_velocity_;
    std::uint8_t first_acceleration_;
    std::uint8_t max_acceleration_;
    std::uint8_t max_deceleration_;
    std::uint8_t first_deceleration_;
    QP::QEQueue target_queues_[constants::prism_count_max];

public:
    Cluster();

protected:
    Q_STATE_DECL(initial);
    Q_STATE_DECL(ClusterOn);
    Q_STATE_DECL(AllPoweredOn);
    Q_STATE_DECL(AllPoweredOff);
}; // class Cluster

} // namespace CC
//$enddecl${AOs::Cluster} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif
