//$file${.::ClusterController.hpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: ClusterController.qm
// File:  ${.::ClusterController.hpp}
//
// This code has been generated by QM 5.2.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::ClusterController.hpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef CLUSTER_CONTROLLER_HPP
#define CLUSTER_CONTROLLER_HPP

#include "qpcpp.hpp"
#include "fsp.hpp"


namespace ArduinoInterface
{
void setup();
void loop();
}

//$declare${Shared} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace CC {

//${Shared::CommandEvt} ......................................................
class CommandEvt : public QP::QEvt {}; // class CommandEvt

//${Shared::EthernetCommandEvt} ..............................................
class EthernetCommandEvt : public QP::QEvt {
public:
    void * connection;
    std::uint8_t const * binary_command;
    std::uint32_t binary_command_byte_count;
}; // class EthernetCommandEvt

//${Shared::PrismCommandEvt} .................................................
class PrismCommandEvt : public QP::QEvt {
public:
    std::uint8_t prism_address;
    std::uint16_t position;
    std::uint8_t speed;
    std::uint8_t current;
    std::int8_t stall_threshold;
}; // class PrismCommandEvt

//${Shared::AO_Cluster} ......................................................
extern QP::QActive * const AO_Cluster;

//${Shared::AO_SerialCommandInterface} .......................................
extern QP::QActive * const AO_SerialCommandInterface;

//${Shared::AO_EthernetCommandInterface} .....................................
extern QP::QActive * const AO_EthernetCommandInterface;

//${Shared::AO_Watchdog} .....................................................
extern QP::QActive * const AO_Watchdog;

//${Shared::Prism_getInstance} ...............................................
QP::QHsm * Prism_getInstance(std::uint8_t prism_address);

} // namespace CC
//$enddecl${Shared} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif
