#ifndef COMMANDS_HPP
#define COMMANDS_HPP


namespace CC
{

enum ClusterControllerCommands
{
  READ_CLUSTER_ADDRESS_CMD = 0x01,
  COMMUNICATING_CLUSTER_CMD = 0x02,
  RESET_CLUSTER_CMD = 0x03,
  BEEP_CLUSTER_CMD = 0x04,
  LED_OFF_CLUSTER_CMD = 0x05,
  LED_ON_CLUSTER_CMD = 0x06,
  POWER_OFF_CLUSTER_CMD = 0x07,
  POWER_ON_CLUSTER_CMD = 0x08,
  HOME_PRISM_CMD = 0x09,
  HOME_CLUSTER_CMD = 0x0A,
  HOMED_CLUSTER_CMD = 0x0B,
  WRITE_TARGET_POSITION_CMD = 0x0C,
  WRITE_ALL_TARGET_POSITIONS_CMD = 0x0D,
  PAUSE_CMD = 0x0E,
  PAUSE_ALL_CMD = 0x0F,
  RESUME_CMD = 0x10,
  RESUME_ALL_CMD = 0x11,
  READ_ALL_ACTUAL_POSITIONS_CMD = 0x12,
};

} // namespace AC

#endif // COMMANDS_HPP
