#ifndef COMMANDS_HPP
#define COMMANDS_HPP


namespace CC
{

enum ClusterControllerCommands
{
  READ_CLUSTER_ADDRESS_CMD = 0x01,
  CHECK_COMMUNICATION_CMD = 0x02,
  RESET_CMD = 0x03,
  BEEP_CMD = 0x04,
  LED_OFF_CMD = 0x05,
  LED_ON_CMD = 0x06,
  POWER_OFF_ALL_CMD = 0x07,
  POWER_ON_ALL_CMD = 0x08,
  HOME_CMD = 0x09,
  HOME_ALL_CMD = 0x0A,
  WRITE_TARGET_POSITION_CMD = 0x0B,
};

} // namespace AC

#endif // COMMANDS_HPP
