//$file${.::Prism.hpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: ClusterController.qm
// File:  ${.::Prism.hpp}
//
// This code has been generated by QM 5.2.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::Prism.hpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef PRISM_HPP
#define PRISM_HPP

#include "ClusterController.hpp"


//============================================================================
// generate declaration of the active object
//$declare${AOs::Prism} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace CC {

//${AOs::Prism} ..............................................................
class Prism : public QP::QHsm {
public:
    static Prism instances[constants::prism_count_max];
    std::uint8_t prism_address_;
    std::uint32_t delay_count_;
    std::uint8_t homed_;
    std::uint8_t home_status_;

public:
    Prism()
      : QHsm(&initial)
    {}

protected:
    Q_STATE_DECL(initial);
    Q_STATE_DECL(PoweredOff);
    Q_STATE_DECL(PoweredOn);
    Q_STATE_DECL(NotSetup);
    Q_STATE_DECL(SetupAndCommunicating);
    Q_STATE_DECL(Enabled);
    Q_STATE_DECL(Homing);
    Q_STATE_DECL(Homed);
    Q_STATE_DECL(WaitingForTarget);
    Q_STATE_DECL(MovingToTarget);
    Q_STATE_DECL(Disconnected);
}; // class Prism

} // namespace CC
//$enddecl${AOs::Prism} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif
