//.$file${.::Prism.hpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: ClusterController.qm
// File:  ${.::Prism.hpp}
//
// This code has been generated by QM 5.1.3 <www.state-machine.com/qm/>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// This program is open source software: you can redistribute it and/or
// modify it under the terms of the GNU General Public License as published
// by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
// for more details.
//
//.$endhead${.::Prism.hpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef PRISM_HPP
#define PRISM_HPP

#include "ClusterController.hpp"


//============================================================================
// generate declaration of the active object
//.$declare${AOs::Prism} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
namespace CC {

//.${AOs::Prism} .............................................................
class Prism : public QP::QHsm {
public:
    static Prism instances[constants::prism_count_max];
    std::uint8_t prism_address_;
    std::uint32_t delay_count_;
    std::uint8_t homed_;

public:
    Prism()
      : QHsm(&initial)
    {}

protected:
    Q_STATE_DECL(initial);
    Q_STATE_DECL(PoweredOff);
    Q_STATE_DECL(PoweredOn);
    Q_STATE_DECL(NotSetup);
    Q_STATE_DECL(SetupAndCommunicating);
    Q_STATE_DECL(Enabled);
    Q_STATE_DECL(Homing);
    Q_STATE_DECL(Homed);
    Q_STATE_DECL(WaitingForTarget);
    Q_STATE_DECL(MovingToTarget);
    Q_STATE_DECL(Disconnected);
};

} // namespace CC
//.$enddecl${AOs::Prism} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif