#ifndef SIGNALS_HPP
#define SIGNALS_HPP

#include "qpcpp.hpp"


namespace CC
{

enum ClusterControllerSignals
{
  // commands from serial or ethernet interface
  RESET_SIG = QP::Q_USER_SIG,
  POWER_ON_SIG,
  POWER_OFF_SIG,

  SERIAL_COMMAND_AVAILABLE_SIG,
  ETHERNET_COMMAND_AVAILABLE_SIG,
  COMMAND_PROCESSED_SIG,

  MAX_PUB_SIG,

  // bsp POST to SerialCommandInterface
  ACTIVATE_SERIAL_COMMAND_INTERFACE_SIG,
  DEACTIVATE_SERIAL_COMMAND_INTERFACE_SIG,
  SERIAL_READY_SIG,

  // bsp POST to EthernetCommandInterface
  ACTIVATE_ETHERNET_COMMAND_INTERFACE_SIG,
  DEACTIVATE_ETHERNET_COMMAND_INTERFACE_SIG,
  ETHERNET_INITIALIZED_SIG,
  ETHERNET_SERVER_INITIALIZED_SIG,

  WATCHDOG_TIMEOUT_SIG,
  SERIAL_TIMEOUT_SIG,
  ETHERNET_TIMEOUT_SIG,

  MAX_SIG
};

} // namespace AC

#endif // SIGNALS_HPP
