#ifndef SIGNALS_HPP
#define SIGNALS_HPP

#include "qpcpp.hpp"


namespace CC
{

enum ClusterControllerSignals
{
  // commands from serial or ethernet interface
  RESET_SIG = QP::Q_USER_SIG,

  SERIAL_COMMAND_AVAILABLE_SIG,
  ETHERNET_COMMAND_AVAILABLE_SIG,
  PROCESS_BINARY_COMMAND_SIG,
  PROCESS_STRING_COMMAND_SIG,
  COMMAND_PROCESSED_SIG,

  MAX_PUB_SIG,

  // POST to Cluster
  CLUSTER_TIMEOUT_SIG,
  POWER_ON_SIG,
  POWER_OFF_SIG,
  HOME_SIG,
  HOMED_SIG,
  WRITE_TARGET_POSITION_SIG,

  // POST to SerialCommandInterface
  SERIAL_TIMEOUT_SIG,
  ACTIVATE_SERIAL_COMMAND_INTERFACE_SIG,
  DEACTIVATE_SERIAL_COMMAND_INTERFACE_SIG,
  SERIAL_READY_SIG,

  // POST to EthernetCommandInterface
  ETHERNET_TIMEOUT_SIG,
  ACTIVATE_ETHERNET_COMMAND_INTERFACE_SIG,
  DEACTIVATE_ETHERNET_COMMAND_INTERFACE_SIG,
  ETHERNET_INITIALIZED_SIG,
  ETHERNET_SERVER_CONNECTED_SIG,

  // POST to Watchdog
  WATCHDOG_TIMEOUT_SIG,

  MAX_SIG
};

} // namespace AC

#endif // SIGNALS_HPP
